### ISSUE TITLE
New scrapped API changes to includes

### ISSUE THREAD

**Issue by vinceh121** [maelgangloff/scolengo-api#34]
- `homework-assignments`: specifying `fields[homework]=title,done,dueDateTime&fields[subject]=label,color` is mandatory, unless the API fails with an NPE
- `homework-assignments/:homeworkId`: include `teacher.person` was removed. I don't think keeping it is an issue?
- `users-mail-settings/:userId`: includes `'contacts', 'contacts.person', 'contacts.personContacts'` were removed. Might be an issue?
- `schools-info`: include `attachments` was removed. Might not be an issue?

Note that the following endpoints were untested:
- `POST communications`
- `GET absence-files/:folderId`

**Comment by maelgangloff** [comment]
Hello Vincent,
Thank you for this detailed information. I'm working on the wrapper to take into account recent API changes.

Thanks again ;)
