### ISSUE TITLE
Unauthorized 403

### ISSUE THREAD

**Issue by malys** [maelgangloff/scolengo-api#37]
**Is your feature request related to a problem? Please describe.**
Authentication

**Describe the solution you'd like**
After 2 years without any problem of authentication, currently, i received 403 http code and it's not possible to use its api anymore.
I have not migrate to new api but I have tried using scolengo and the same 403.

**Describe alternatives you've considered**
no workaround possible

Any ideas?

**Comment by maelgangloff** [comment]
Hello,
It seems that the migration to the new Skolengo API has started. So I moved this issue to the *scolengo-api* project.
**Can you describe the steps to reproduce the error?**

The authentication mechanism of the new API is very different compared to the old one (based on *OpenID Connect*). If you need help, don't hesitate to join the Discord group to ask any questions you may have. Feel free to join the Discord group if you would like help with your project.

**Comment by malys** [comment]
After the export to token, I have created  js file for testing.
```
const config = {
    "tokenSet": {
        "token_type": "Bearer",
        "expires_at": 1701852008,
        "scope": "openid"
    },
    "school": {
        "id": "SKO-E-d7f8f97d-c455-44b9-99cb-7f180cd1cb7b",
        "name": "Collège René Cassin",
        "addressLine1": "Avenue DES CARABENES",
        "addressLine2": null,
        "addressLine3": null,
        "zipCode": "31650",
        "city": "ST ORENS DE GAMEVILLE",
        "country": "France",
        "homePageUrl": "https://cas.ecollege.haute-garonne.fr/login?service=https%3A%2F%2Frene-cassin.ecollege.haute-garonne.fr%2Fsg.do%3FPROC%3DPAGE_ACCUEIL",
        "emsCode": "cg31",
        "emsOIDCWellKnownUrl": "https://sso.ecollege.haute-garonne.fr/oidc/.well-known"
    }
}
Skolengo.fromConfigObject(config).then(async user => {
    const infoUser = await user.getUserInfo()
```
This code worked fine in September.

But currenlty, it returns

````

FORBIDDEN: Access is denied
    at Skolengo.request (B:\prog\nodejs\node-red\node_modules\scolengo-api\dist\index.js:1023:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Skolengo.getHomeworkAssignments (B:\prog\nodejs\node-red\node_modules\scolengo-api\dist\index.js:583:52)
    at async B:\prog\nodejs\node-red\college2.js:79:22 {
  status: '403',
  detail: 'Access is denied',
  title: 'FORBIDDEN'
}
```
Today, I have tried to regenerate my oidc Authn token and not authorized.

**Comment by maelgangloff** [comment]
The tokenSet is valid for **24 hours**. You must refresh the token after this date and store the value of the new tokenSet somewhere.

The *refresh* is done automatically by *scolengo-api* when it gets an HTTP 403 error from the API.
You can specify a function [(*onTokenRefresh*)](https://github.com/maelgangloff/scolengo-api#skolengorefreshtokentriggerlistener) that will be called on refresh. It is common for this function to be used to store the new value of the tokenSet.

I see you are using node-red for automation, I don't know how to implement this with this tool but I think it is possible.

**Comment by malys** [comment]
I know very well oidc and I have integrated it in nodered.
Next step is to spend time on the migration ;(
Thanks for your help.
